# Generated by Django 5.0.1 on 2024-01-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(blank=True, max_length=64, null=True)),
                ("alias", models.CharField(blank=True, max_length=64, null=True)),
                ("id_card", models.IntegerField(blank=True, null=True, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=13, null=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
