# Generated by Django 5.0.1 on 2024-01-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0003_alter_category_name_alter_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Processing"),
                            (2, "Successful"),
                            (3, "Failed"),
                            (4, "Cancel"),
                        ]
                    ),
                ),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Delivered"),
                            (2, "Picked"),
                            (3, "Cancel"),
                        ]
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_attributes", models.JSONField(blank=True)),
                ("quantity", models.IntegerField(default=1)),
                ("subtotal", models.FloatField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "order")},
            },
        ),
    ]
