# Generated by Django 5.0.1 on 2024-01-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_category_added_on_alter_product_added_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="symbol",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
